### ISSUE TITLE
FindNV throws error if plotted from Dataset

### ISSUE THREAD

**Issue by asafira** [LISE-B26/b26_toolkit#10]
If FindNV is sent to Dataset, an error is thrown once you click on it (i.e., when the gui tries to plot it):

Traceback (most recent call last):
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 174, in <lambda>
    self.tree_dataset.clicked.connect(lambda: self.btn_clicked())
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 746, in btn_clicked
    plot_data(sender)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 735, in plot_data
    self.plot_script(script)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 896, in plot_script
    script.plot([self.matplotlibwidget_1.figure, self.matplotlibwidget_2.figure])
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\core\scripts.py", line 1124, in plot
    self._plot(axes_list)
  File "C:\Users\Experiment\PycharmProjects\b26_toolkit\src\scripts\find_nv.py", line 150, in _plot
    if self._current_subscript_stage['current_subscript'] == self.scripts['take_image']:
AttributeError: 'FindNV' object has no attribute '_current_subscript_stage'

There are not issues re-plotting using the "plot script" button in the script tab.

**Comment by JanGieseler** [comment]
I think I know how to fix this. The problem is that the script doesn't keep the image data. So what I would do it to get it from the image itself when you execute the script and save it in self.data
