### ISSUE TITLE
Cannot replot pulsed experiment data

### ISSUE THREAD

**Issue by asafira** [LISE-B26/b26_toolkit#33]
Currently, we cannot replot pulsed experiment scripts saved to Dataset.

Example path to reach bug:

1) Run a readout_T_double_init
2) send it to dataset
3) run another readout_T_double_init experiment
4) send it to dataset
5) try plotting the original readout_T_double_init experiment, and the error will pop up.

Specific error:
Traceback (most recent call last):
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 198, in <lambda>
    self.tree_dataset.clicked.connect(lambda: self.btn_clicked())
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 814, in btn_clicked
    plot_data(sender)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 796, in plot_data
    self.plot_script(script)
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\gui\qt_b26_gui.py", line 966, in plot_script
    script.plot([self.matplotlibwidget_1.figure, self.matplotlibwidget_2.figure])
  File "C:\Users\Experiment\PycharmProjects\PyLabControl\src\core\scripts.py", line 1352, in plot
    self._plot(axes_list)
  File "C:\Users\Experiment\PycharmProjects\b26_toolkit\src\scripts\pulse_blaster_scripts.py", line 1286, in _plot
    super(readout_T_double_init, self)._plot(axislist)
  File "C:\Users\Experiment\PycharmProjects\b26_toolkit\src\scripts\pulse_blaster_base_script.py", line 178, in _plot
    plot_pulses(axis2, self.pulse_sequences[self.sequence_index])
AttributeError: 'readout_T_double_init' object has no attribute 'pulse_sequences'

**Comment by asafira** [comment]
I should re-test this given the changes I've made recently. This looks like an easy bug to fix.
