### ISSUE TITLE
SMC motor not working:  The specified port is not open

### ISSUE THREAD

**Issue by JanGieseler** [LISE-B26/b26_toolkit#50]
running script SMCAutofocus give following error
**Traceback:**

module b26_toolkit.scripts.autofocus
module b26_toolkit.scripts.take_image_camera
ERROR: 1TP command: -100 => The specified port is not open
Traceback (most recent call last):
  File "C:\Users\NV Experiment\PycharmProjects\pylabcontrol\pylabcontrol\gui\windows_and_widgets\main_window.py", line 179, in <lambda>
    self.tree_settings.itemExpanded.connect(lambda: self.refresh_instruments())
  File "C:\Users\NV Experiment\PycharmProjects\pylabcontrol\pylabcontrol\gui\windows_and_widgets\main_window.py", line 387, in refresh_instruments
    update(instrument)
  File "C:\Users\NV Experiment\PycharmProjects\pylabcontrol\pylabcontrol\gui\windows_and_widgets\main_window.py", line 374, in update
    value = instrument.read_probes(path_to_instrument[-1])
  File "C:\Users\NV Experiment\PycharmProjects\b26_toolkit\b26_toolkit\instruments\newport_smc100.py", line 115, in read_probes
    return self._get_position()*1e3
  File "C:\Users\NV Experiment\PycharmProjects\b26_toolkit\b26_toolkit\instruments\newport_smc100.py", line 138, in _get_position
    raise ValueError('ERROR: ' + errString)
ValueError: ERROR: 1TP command: -100 => The specified port is not open

**Comment by JanGieseler** [comment]
related issue: setting the position below `height_lower_limit` crashed the gui. This should be handle more gracefully

**Traceback**

Traceback (most recent call last):
  File "C:\Users\NV Experiment\PycharmProjects\pylabcontrol\pylabcontrol\gui\windows_and_widgets\main_window.py", line 1171, in <lambda>
    tree.itemChanged.connect(lambda: self.update_parameters(tree))
  File "C:\Users\NV Experiment\PycharmProjects\pylabcontrol\pylabcontrol\gui\windows_and_widgets\main_window.py", line 902, in update_parameters
    instrument.update(dictator)
  File "C:\Users\NV Experiment\PycharmProjects\b26_toolkit\b26_toolkit\instruments\newport_smc100.py", line 91, in update
    self._set_position(value/1e3)
  File "C:\Users\NV Experiment\PycharmProjects\b26_toolkit\b26_toolkit\instruments\newport_smc100.py", line 150, in _set_position
    raise ValueError('cannot set position below height_lower_limit')
ValueError: cannot set position below height_lower_limit
